const HOME="https://www.google.com/";const SEARCH="https://www.google.com/search?q=";
const S={tabs:[],active:0,next:1,bookmarks:JSON.parse(localStorage.getItem("chromium-bookmarks")||"[]"),history:JSON.parse(localStorage.getItem("chromium-history")||"[]"),downloads:JSON.parse(localStorage.getItem("chromium-downloads")||"[]")};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],E=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const I=n=>`<svg><use href="/assets/icons.svg#${n}"/></svg>`;const save=(k,v)=>localStorage.setItem("chromium-"+k,JSON.stringify(v));
function norm(v){v=v.trim();if(!v)return HOME;if(/^[a-z][a-z0-9+.-]*:/i.test(v))return v;if(v.includes(".")&&!v.includes(" "))return"https://"+v;return SEARCH+encodeURIComponent(v)}
function domain(u){try{return new URL(u).hostname}catch{return""}}function cur(){return S.tabs[S.active]}
function makeTab(url=HOME){const t={id:S.next++,url,title:"New Tab",frame:null,loading:false};S.tabs.push(t);S.active=S.tabs.length-1;renderTabs();mount(t)}
function mount(t){$$(".frame").forEach(x=>x.classList.remove("active"));const f=document.createElement("controlledframe");f.className="frame active";f.partition="persist:chromium";f.setAttribute("allowfullscreen","");f.src=t.url;
f.addEventListener("loadstart",()=>{t.loading=true;update()});f.addEventListener("loadcommit",()=>sync(t,f));f.addEventListener("loadstop",()=>sync(t,f));f.addEventListener("loadabort",()=>{t.loading=false;update()});f.addEventListener("newwindow",e=>{e.preventDefault();makeTab(e.targetUrl||HOME)});f.addEventListener("permissionrequest",e=>permission(t,e));$("#frames").appendChild(f);t.frame=f;sync(t,f)}
async function sync(t,f){t.url=f.src||t.url;t.loading=false;try{let r=await f.executeScript({code:"document.title||location.hostname"});t.title=(Array.isArray(r)?r[0]:r)||domain(t.url)||"New Tab"}catch{t.title=domain(t.url)||"New Tab"}if(/^https?:/.test(t.url)&&domain(t.url)){if(!S.history[0]||S.history[0].url!==t.url){S.history.unshift({url:t.url,title:t.title,time:Date.now()});S.history=S.history.slice(0,500);save("history",S.history)}}renderTabs();update()}
function renderTabs(){const b=$("#tabs");b.innerHTML="";S.tabs.forEach((t,i)=>{const d=document.createElement("div");d.className="tab"+(i===S.active?" active":"");d.innerHTML=`<span class="favicon">${domain(t.url)?`<img src="https://www.google.com/s2/favicons?domain=${encodeURIComponent(domain(t.url))}&sz=32">`:"●"}</span><span class="title">${E(t.title)}</span><button class="tabclose">${I("close")}</button>`;d.onclick=e=>{if(!e.target.closest(".tabclose"))activate(i)};d.querySelector(".tabclose").onclick=e=>{e.stopPropagation();closeTab(i)};d.oncontextmenu=e=>{e.preventDefault();tabContext(i,e.clientX,e.clientY)};b.appendChild(d)})}
function activate(i){S.active=i;$$(".frame").forEach((x,n)=>x.classList.toggle("active",n===i));renderTabs();update();closePopups();$("#addr").blur()}
function closeTab(i){if(S.tabs.length===1)return cur().frame.reload();S.tabs[i].frame?.remove();S.tabs.splice(i,1);S.active=Math.max(0,Math.min(S.active,S.tabs.length-1));activate(S.active)}
function update(){const t=cur();if(!t)return;$("#addr").value=t.url;$("#reload").innerHTML=I(t.loading?"close":"refresh");$("#star").classList.toggle("saved",S.bookmarks.some(b=>b.url===t.url));$("#back").disabled=false;$("#forward").disabled=false}
function nav(v){const u=norm(v);cur().url=u;cur().frame.src=u;$("#addr").value=u;$("#suggestions").classList.remove("open")}
async function go(m){try{await cur().frame[m]()}catch{}}
function closePopups(){["menu","ctx","bubble","suggestions"].forEach(x=>$("#"+x).classList.remove("open"))}
function mi(label,ic,fn,key=""){const b=document.createElement("button");b.className="mi";b.innerHTML=`${I(ic)}<span>${E(label)}</span>${key?`<span class="shortcut">${E(key)}</span>`:""}`;b.onclick=()=>{fn?.();closePopups()};return b}
function sep(){const d=document.createElement("div");d.className="sep";return d}
function showMenu(){
 const p=$("#menu"); p.innerHTML="";
 p.append(mi("New tab","add",()=>makeTab(),"Ctrl+T"),mi("New window","browser_tools",()=>window.open("/unframed/window.html","_blank"),"Ctrl+N"),mi("New Incognito window","incognito",()=>window.open("/unframed/window.html?incognito=1","_blank"),"Ctrl+Shift+N"));
 p.append(sep(),mi("History","history",history,"Ctrl+H"),mi("Downloads","download",downloads,"Ctrl+J"),mi("Bookmarks and lists","bookmark",bookmarks,"Ctrl+Shift+O"));
 p.append(sep(),mi("Find…","search",find,"Ctrl+F"),mi("Print…","print",printPage,"Ctrl+P"),mi("Create QR code for this page","qr",()=>info("QR code",cur().url)),mi("Save page as…","download",savePage,"Ctrl+S"));
 p.append(sep(),mi("More tools","settings",moreTools),mi("Settings","settings",settings),mi("Help","search",()=>info("Help","Everyday shortcuts: Ctrl+L address bar · Ctrl+T new tab · Ctrl+W close · Ctrl+Shift+T reopen · Ctrl+D bookmark · Ctrl+F find · Ctrl+J downloads · Ctrl+H history · Ctrl+P print")),mi("About Chromium","security",()=>info("About Chromium","Chromium IWA\n\nA borderless IWA shell using Controlled Frame for website content.")));
 p.classList.add("open");
}
function moreTools(){const p=$("#menu");p.innerHTML="";p.append(mi("Extensions","extensions",extensions),mi("Clear browsing data…","settings",clearData),mi("Task manager","search",()=>info("Task manager","Native Chromium task/process metrics require privileged browser APIs.")),sep(),mi("Developer tools","settings",()=>info("Developer tools","DevTools is a privileged Chromium surface and is not embeddable in an IWA.")));p.classList.add("open")}
function tabContext(i,x,y){const p=$("#ctx"),t=S.tabs[i];p.innerHTML="";p.append(mi("New tab","add",()=>makeTab()),mi("Reload","refresh",()=>t.frame?.reload()),mi("Duplicate","copy",()=>makeTab(t.url)),mi(t.pinned?"Unpin tab":"Pin tab","bookmark",()=>t.pinned=!t.pinned),mi(t.muted?"Unmute site":"Mute site","security",()=>t.muted=!t.muted),sep(),mi("Move tab to new window","browser_tools",()=>window.open("/unframed/window.html?url="+encodeURIComponent(t.url),"_blank")),mi("Close tab","close",()=>closeTab(i),"Ctrl+W"),mi("Close other tabs","close",()=>{const keep=S.tabs[i];S.tabs.forEach(x=>{if(x!==keep)x.frame?.remove()});S.tabs=[keep];S.active=0;renderTabs();update()}),mi("Reopen closed tab","history",()=>makeTab(S.history.find(x=>x.closed)?.url||HOME)));p.style.left=Math.min(innerWidth-260,Math.max(5,x))+"px";p.style.top=Math.min(innerHeight-360,Math.max(40,y))+"px";p.classList.add("open")}
function suggestions(){const q=$("#addr").value.trim().toLowerCase();if(!q)return $("#suggestions").classList.remove("open");let a=[],seen=new Set();const add=(text,url,ic)=>{if(!seen.has(url)){seen.add(url);a.push({text,url,ic})}};S.bookmarks.filter(x=>(x.title+" "+x.url).toLowerCase().includes(q)).slice(0,4).forEach(x=>add(x.title,x.url,"bookmark"));S.history.filter(x=>(x.title+" "+x.url).toLowerCase().includes(q)).slice(0,5).forEach(x=>add(x.title,x.url,"history"));add($("#addr").value,norm($("#addr").value),"search");$("#suggestions").innerHTML=a.slice(0,8).map(x=>`<div class="sug" data-u="${E(x.url)}">${I(x.ic)}<span class="sugmain">${E(x.text)}</span><span class="sugsub">${E(x.url)}</span></div>`).join("");$$(".sug").forEach(x=>x.onclick=()=>nav(x.dataset.u));$("#suggestions").classList.add("open")}
function bookmark(){const t=cur(),i=S.bookmarks.findIndex(x=>x.url===t.url);if(i>=0)S.bookmarks.splice(i,1);else S.bookmarks.unshift({url:t.url,title:t.title});save("bookmarks",S.bookmarks);update();bubble(i<0?"Bookmark added":"Removed from bookmarks",t.title)}
function security(){const u=cur().url;$("#bubble").innerHTML=`<div class="bt">${I("security")} ${/^https:/.test(u)?"Connection is secure":"Connection is not secure"}</div><div class="bx"><b>${E(domain(u)||"This page")}</b><br><br>This Chromium-style page-info surface shows the security state of the embedded page. Permissions and storage remain controlled by the Controlled Frame partition.</div><div class="ba"><button class="secondary" id="site">Site settings</button><button id="done">Done</button></div>`;$("#bubble").style.right="150px";$("#bubble").style.top="84px";$("#bubble").classList.add("open");$("#done").onclick=closePopups;$("#site").onclick=()=>info("Site settings",domain(u))}
function bubble(title,text){$("#bubble").innerHTML=`<div class="bt">${E(title)}</div><div class="bx">${E(text)}</div><div class="ba"><button id="bdone">Done</button></div>`;$("#bubble").style.right="150px";$("#bubble").style.top="84px";$("#bubble").classList.add("open");$("#bdone").onclick=closePopups}
function modal(title,html,fn){$("#mt").textContent=title;$("#mb").innerHTML=html;$("#mb").onclick=fn||null;$("#modal").style.display="flex"}function info(t,m){modal(t,`<div style="white-space:pre-wrap;line-height:1.55;color:#d7d9dc">${E(m)}</div>`)}
function bookmarks(){const r=S.bookmarks.map((b,i)=>`<div class="row" data-i="${i}">${I("bookmark")}<div class="rm"><div class="rt">${E(b.title)}</div><div class="rs">${E(b.url)}</div></div></div>`).join("")||'<div class="empty">No bookmarks yet.</div>';modal("Bookmarks and lists",r,e=>{const i=e.target.closest("[data-i]")?.dataset.i;if(i!=null){nav(S.bookmarks[i].url);$("#modal").style.display="none"}})}
function history(){const r=S.history.map((h,i)=>`<div class="row" data-i="${i}">${I("history")}<div class="rm"><div class="rt">${E(h.title)}</div><div class="rs">${E(h.url)}</div></div></div>`).join("")||'<div class="empty">No history yet.</div>';modal("History",r,e=>{const i=e.target.closest("[data-i]")?.dataset.i;if(i!=null){nav(S.history[i].url);$("#modal").style.display="none"}})}
function downloads(){const r=S.downloads.map(d=>`<div class="row">${I("download")}<div class="rm"><div class="rt">${E(d.name||d.url)}</div><div class="rs">${E(d.url)} · ${new Date(d.time).toLocaleString()}</div></div></div>`).join("")||'<div class="empty">No downloads yet.</div>';modal("Downloads",r)}
function extensions(){modal("Extensions",`<div class="row">${I("extensions")}<div class="rm"><div class="rt">IWA browser tools</div><div class="rs">Chromium-style extension controls</div></div></div><div class="row">${I("extensions")}<div class="rm"><div class="rt">Manage extensions</div><div class="rs">Native Chrome extension installation requires privileged Chromium extension APIs.</div></div></div>`)}
function settings(){modal("Settings",`<div class="row">${I("person")}<div class="rm"><div class="rt">You and Chromium</div><div class="rs">Profile and personalization</div></div></div><div class="row">${I("security")}<div class="rm"><div class="rt">Privacy and security</div><div class="rs">Clear data, permissions, and site settings</div></div></div><div class="row">${I("settings")}<div class="rm"><div class="rt">Appearance</div><div class="rs">Theme and toolbar controls</div></div></div>`)}
function tabSearch(){modal("Search tabs",`<input id="tq" style="width:100%;height:40px;background:#202124;border:1px solid #5f6368;border-radius:9px;color:#e8eaed;padding:0 12px;outline:none" placeholder="Search tabs"><div id="tr" style="margin-top:10px"></div>`);const render=()=>{$("#tr").innerHTML=S.tabs.map((t,i)=>`<div class="row" data-i="${i}">${I("search")}<div class="rm"><div class="rt">${E(t.title)}</div><div class="rs">${E(t.url)}</div></div></div>`).join("");$$("#tr [data-i]").forEach(x=>x.onclick=()=>{activate(+x.dataset.i);$("#modal").style.display="none"})};$("#tq").oninput=render;render();$("#tq").focus()}
function find(){const q=prompt("Find in page");if(q)cur().frame.executeScript({code:`window.find(${JSON.stringify(q)})`})}function printPage(){cur().frame.executeScript({code:"window.print()"})}function savePage(){S.downloads.unshift({name:(cur().title||"page")+".html",url:cur().url,time:Date.now()});save("downloads",S.downloads);info("Save page","The save-page request was recorded in the IWA download surface. Full browser file writing requires the host download API.")}async function clearData(){try{await cur().frame.clearData()}catch{}S.history=[];save("history",[]);info("Clear browsing data","Controlled Frame storage and browser-shell history were cleared.")}
function permission(t,e){const p=document.createElement("div");p.className="perm";p.innerHTML=`<div class="permhead">${I("security")}<b>Allow ${E(e.permission||"permission")}?</b></div><div class="permsub">${E(domain(t.url))}</div><div class="actions"><button class="deny">Block</button><button class="allow">Allow</button></div>`;$("#perms").appendChild(p);p.querySelector(".deny").onclick=()=>{try{e.request.deny()}catch{}p.remove()};p.querySelector(".allow").onclick=()=>{try{e.request.allow()}catch{}p.remove()}}
document.addEventListener("DOMContentLoaded",()=>{makeTab();$("#back").onclick=()=>go("back");$("#forward").onclick=()=>go("forward");$("#reload").onclick=()=>cur().frame.reload();$("#home").onclick=()=>nav(HOME);$("#star").onclick=bookmark;$("#security").onclick=security;$("#menub").onclick=showMenu;$("#downloads").onclick=downloads;$("#extensions").onclick=extensions;$("#profile").onclick=()=>info("Profile","Chromium profile\n\nPersistent Controlled Frame storage is enabled.");$("#tabsearch").onclick=tabSearch;$("#newtab").onclick=()=>makeTab();$("#mx").onclick=()=>$("#modal").style.display="none";$("#close").onclick=()=>window.close();$("#min").onclick=()=>info("Minimize","The IWA standard does not expose a portable minimize API; this control remains in the borderless window chrome.");$("#max").onclick=()=>info("Maximize","The IWA standard does not expose a portable maximize API; this control remains in the borderless window chrome.");
$("#addr").addEventListener("focus",()=>{$("#omnibox").classList.add("focused");suggestions()});$("#addr").addEventListener("input",suggestions);$("#addr").addEventListener("keydown",e=>{if(e.key==="Enter"){nav(e.target.value);e.target.blur()}if(e.key==="Escape"){e.target.value=cur().url;e.target.blur();closePopups()}});
document.addEventListener("click",e=>{if(!e.target.closest("#omnibox")&&!e.target.closest("#suggestions"))$("#suggestions").classList.remove("open");if(!e.target.closest("#ctx"))$("#ctx").classList.remove("open")});
document.addEventListener("keydown",e=>{const m=e.ctrlKey||e.metaKey,k=e.key.toLowerCase();if(m&&k==="l"){e.preventDefault();$("#addr").focus();$("#addr").select()}if(m&&k==="t"){e.preventDefault();makeTab()}if(m&&k==="w"){e.preventDefault();closeTab(S.active)}if(m&&e.shiftKey&&k==="t"){e.preventDefault();makeTab(S.history.find(x=>x.closed)?.url||HOME)}if(m&&k==="r"){e.preventDefault();cur().frame.reload()}if(m&&k==="d"){e.preventDefault();bookmark()}if(m&&k==="f"){e.preventDefault();find()}if(m&&k==="j"){e.preventDefault();downloads()}if(m&&k==="h"){e.preventDefault();history()}if(m&&k==="p"){e.preventDefault();printPage()}if(e.altKey&&e.key==="ArrowLeft"){e.preventDefault();go("back")}if(e.altKey&&e.key==="ArrowRight"){e.preventDefault();go("forward")}})});
